"""SEO engine — generate programmatic landing pages from the live tender data.

Distribution is the whole game, and the only channel is content/SEO. This turns
the live contract database into hundreds of genuinely useful long-tail pages —
one per sector, region and major buyer — each listing real current opportunities
and funnelling to the BidBeacon tool. Every page is regenerated by the nightly
cron, so they stay fresh (stale listings are what gets auto-pages de-indexed).

    PYTHONPATH=. python3 -m radar.seo            # reads site/tenders.json -> site/seo/

Quality guardrails (so Google treats these as useful, not thin/spam):
  - a page is only generated when it has at least MIN_ITEMS real live listings;
  - each intro states real, page-specific facts (counts, value range, top buyers);
  - pages interlink, and all link to the live tool.
"""
from __future__ import annotations
import html
import json
import re
from datetime import date
from pathlib import Path

from .ocds import CPV_DIVISIONS


def canonical_sector(t: dict) -> str | None:
    """One sector label per CPV division, regardless of which feed it came from
    — stops the two sources' different CPV text creating duplicate pages."""
    div = (t.get("cpv2") or "")[:2]
    return CPV_DIVISIONS.get(div) or t.get("sector")

ROOT = Path(__file__).parent.parent
SITE = ROOT / "site"
OUT = SITE / "seo"
MIN_ITEMS = 3
TOOL_URL = "../bidbeacon.html"   # relative within site/

CSS = """
:root{--bg:#f4f6f8;--surface:#fff;--ink:#141a26;--muted:#5a6475;--line:#dfe4ea;--accent:#c9741a;--accent-ink:#2a1800;
--sans:"IBM Plex Sans",system-ui,-apple-system,Segoe UI,Roboto,sans-serif;--mono:"IBM Plex Mono",ui-monospace,Menlo,monospace}
@media(prefers-color-scheme:dark){:root:not([data-theme=light]){--bg:#0d1117;--surface:#151b23;--ink:#e8ecf2;--muted:#9aa4b2;--line:#27303b;--accent:#f0a63a;--accent-ink:#241600;color-scheme:dark}}
*{box-sizing:border-box}body{background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.6;margin:0}
.wrap{max-width:860px;margin:0 auto;padding-inline:16px}a{color:var(--accent)}
header{border-bottom:1px solid var(--line);background:var(--surface)}
header .wrap{display:flex;align-items:center;gap:9px;padding-block:12px}
.beacon{width:16px;height:16px;border-radius:50%;background:var(--accent);box-shadow:0 0 0 3px color-mix(in srgb,var(--accent) 28%,transparent)}
.brand{font-weight:700;color:var(--ink);text-decoration:none}
h1{font-size:clamp(1.4rem,4vw,2rem);letter-spacing:-.02em;text-wrap:balance;margin:26px 0 8px}
.lede{color:var(--muted);margin:0 0 4px;max-width:65ch}.upd{color:var(--muted);font-size:.78rem;font-family:var(--mono);margin-top:8px}
.cta{display:flex;flex-wrap:wrap;gap:10px 14px;align-items:center;background:var(--surface);border:1px solid var(--line);border-left:4px solid var(--accent);border-radius:12px;padding:14px;margin:18px 0}
.cta .price{font-family:var(--mono);color:var(--accent);font-weight:600}
.btn{font:inherit;font-weight:600;background:var(--accent);color:var(--accent-ink);text-decoration:none;border-radius:9px;padding:9px 15px}
ul.list{list-style:none;padding:0;margin:14px 0;display:flex;flex-direction:column;gap:10px}
li.item{background:var(--surface);border:1px solid var(--line);border-radius:10px;padding:12px 14px}
li.item a{color:var(--ink);font-weight:600;text-decoration:none}li.item a:hover{text-decoration:underline;text-decoration-color:var(--accent)}
.meta{color:var(--muted);font-size:.82rem;margin-top:5px;font-family:var(--mono)}
nav.related{border-top:1px solid var(--line);margin-top:26px;padding-top:16px}
nav.related a{display:inline-block;margin:0 10px 8px 0;font-size:.85rem}
footer{color:var(--muted);font-size:.76rem;border-top:1px solid var(--line);margin-top:26px;padding-block:18px 40px;line-height:1.6}
"""


def slug(s: str) -> str:
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", (s or "").lower())).strip("-")[:60] or "x"


def _gbp(v):
    return f"£{round(v):,}" if isinstance(v, (int, float)) else "value not stated"


def page(title, desc, h1, lede, items, related, depth=1):
    pre = "../" * depth
    rows = []
    for t in items[:60]:
        loc = t.get("locality") or ""
        rows.append(
            f'<li class="item"><a href="{html.escape(t.get("url") or "#")}" target="_blank" rel="noopener">'
            f'{html.escape(t.get("title") or "Untitled")}</a>'
            f'<div class="meta">{html.escape(t.get("buyer") or "")} · {_gbp(t.get("value"))} · '
            f'closes {t.get("deadline") or "n/a"}{" · "+html.escape(loc) if loc else ""}</div></li>')
    rel = "".join(f'<a href="{pre}seo/{href}">{html.escape(txt)}</a>' for txt, href in related)
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title><meta name="description" content="{html.escape(desc)}">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@500&family=IBM+Plex+Sans:wght@400;600;700&display=swap">
<style>{CSS}</style></head><body>
<header><div class="wrap"><span class="beacon"></span><a class="brand" href="{pre}bidbeacon.html">BidBeacon</a></div></header>
<main class="wrap">
<h1>{html.escape(h1)}</h1>
<p class="lede">{html.escape(lede)}</p>
<p class="upd">Updated {date.today().isoformat()} · live from Public Contracts Scotland &amp; Contracts Finder</p>
<div class="cta"><strong>Get these matched to your business</strong>
<span class="price">£19/mo founding rate</span>
<a class="btn" href="{pre}bidbeacon.html">Search &amp; match free →</a></div>
<ul class="list">{"".join(rows)}</ul>
<nav class="related"><strong style="display:block;margin-bottom:8px;font-size:.85rem">More live opportunities</strong>{rel}</nav>
</main>
<footer><div class="wrap">Contains public sector information licensed under the Open Government Licence v3.0.
BidBeacon is independent and not affiliated with GOV.UK, the Scottish Government or any buyer.</div></footer>
</body></html>"""


def md_to_html(md: str) -> str:
    """Minimal Markdown → HTML for our own controlled article content:
    #/##/### headings, paragraphs, - lists, 1. lists, **bold**, [text](url), ---."""
    def inline(s):
        s = html.escape(s)
        s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
        s = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', s)
        return s
    out, lst = [], None
    def close():
        nonlocal lst
        if lst: out.append(f"</{lst}>"); lst = None
    for raw in md.splitlines():
        line = raw.rstrip()
        if not line: close(); continue
        if line == "---": close(); out.append("<hr>"); continue
        m = re.match(r"(#{1,3}) (.+)", line)
        if m: close(); out.append(f"<h{len(m.group(1))}>{inline(m.group(2))}</h{len(m.group(1))}>"); continue
        m = re.match(r"- (.+)", line)
        if m:
            if lst != "ul": close(); out.append("<ul>"); lst = "ul"
            out.append(f"<li>{inline(m.group(1))}</li>"); continue
        m = re.match(r"\d+\. (.+)", line)
        if m:
            if lst != "ol": close(); out.append("<ol>"); lst = "ol"
            out.append(f"<li>{inline(m.group(1))}</li>"); continue
        close(); out.append(f"<p>{inline(line)}</p>")
    close()
    return "\n".join(out)


def article_page(title, desc, body_html, related, depth=2):
    pre = "../" * depth
    rel = "".join(f'<a href="{pre}{href}">{html.escape(txt)}</a>' for txt, href in related)
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title><meta name="description" content="{html.escape(desc)}">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@500&family=IBM+Plex+Sans:wght@400;600;700&display=swap">
<style>{CSS}
article h2{{font-size:1.25rem;margin:26px 0 6px;letter-spacing:-.01em}}article h3{{font-size:1.05rem;margin:20px 0 4px}}
article p,article li{{max-width:68ch}}article ul,article ol{{padding-left:22px}}article li{{margin:4px 0}}</style></head><body>
<header><div class="wrap"><span class="beacon"></span><a class="brand" href="{pre}bidbeacon.html">BidBeacon</a></div></header>
<main class="wrap"><article>{body_html}</article>
<div class="cta"><strong>See which of these contracts fit your business</strong>
<span class="price">£19/mo founding rate</span>
<a class="btn" href="{pre}bidbeacon.html">Search &amp; match free →</a></div>
<nav class="related"><strong style="display:block;margin-bottom:8px;font-size:.85rem">More</strong>{rel}</nav></main>
<footer><div class="wrap">Contains public sector information licensed under the Open Government Licence v3.0.
BidBeacon is independent and not affiliated with GOV.UK, the Scottish Government or any buyer.
This guide is general information, not legal or procurement advice.</div></footer>
</body></html>"""


def _render_content(subdir: str, related):
    """Render content/<subdir>/*.md (first line '# Title', second line '> desc')
    into site/seo/<subdir>/*.html. Returns [(title, 'seo/<subdir>/<slug>.html')]."""
    src = ROOT / "content" / subdir
    if not src.exists():
        return []
    (OUT / subdir).mkdir(parents=True, exist_ok=True)
    links = []
    for md_file in sorted(src.glob("*.md")):
        lines = md_file.read_text().splitlines()
        title = lines[0].lstrip("# ").strip()
        desc = lines[1].lstrip("> ").strip() if len(lines) > 1 and lines[1].startswith(">") else title
        body = md_to_html("\n".join(lines[2:] if desc != title else lines[1:]))
        (OUT / subdir / f"{md_file.stem}.html").write_text(
            article_page(f"{title} | BidBeacon", desc, f"<h1>{html.escape(title)}</h1>\n{body}",
                         related, depth=2))
        links.append((title, f"seo/{subdir}/{md_file.stem}.html"))
    return links


def build() -> dict:
    tenders = json.load(open(SITE / "tenders.json"))
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "sector").mkdir(exist_ok=True)
    (OUT / "region").mkdir(exist_ok=True)
    (OUT / "buyer").mkdir(exist_ok=True)

    def group(key):
        g = {}
        for t in tenders:
            k = key(t)
            if k:
                g.setdefault(k, []).append(t)
        return {k: v for k, v in g.items() if len(v) >= MIN_ITEMS}

    REGION = {"ne": "Aberdeen & North-East Scotland", "scot": "Scotland", "uk": "UK-wide"}
    def region_key(t):
        n = (t.get("nuts") or "").upper(); c = (t.get("country") or "").upper()
        if n.startswith("UKM5"): return "ne"
        if n.startswith("UKM"): return "scot"
        if n == "UK" or c in ("GB", "UNITED KINGDOM", ""): return "uk"
        return None

    sectors = group(canonical_sector)
    regions = group(region_key)
    buyers = dict(sorted(group(lambda t: t.get("buyer")).items(),
                         key=lambda kv: -len(kv[1]))[:12])

    # related links shared across pages
    rel_sectors = [(f"{s} contracts", f"sector/{slug(s)}.html") for s in list(sectors)[:8]]
    rel_regions = [(REGION[r], f"region/{r}.html") for r in regions]

    def valrange(items):
        vals = [t["value"] for t in items if isinstance(t.get("value"), (int, float))]
        return f"{_gbp(min(vals))}–{_gbp(max(vals))}" if vals else "a range of values"

    n = 0
    for s, items in sectors.items():
        top = ", ".join(sorted({t["buyer"] for t in items if t.get("buyer")})[:3])
        lede = (f"{len(items)} open {s.lower()} public-sector contracts in Scotland and the UK, "
                f"worth {valrange(items)}. Buyers include {top}. Updated daily.")
        (OUT / "sector" / f"{slug(s)}.html").write_text(page(
            f"{s} public contracts in Scotland — live tenders | BidBeacon",
            lede, f"{s} public contracts", lede, items,
            rel_regions + [(f"{x} contracts", f"sector/{slug(x)}.html") for x in sectors if x != s][:6],
            depth=2)); n += 1

    for r, items in regions.items():
        lede = (f"{len(items)} open public-sector contracts for {REGION[r]}, across sectors from "
                f"construction to IT, worth {valrange(items)}. Updated daily from official sources.")
        (OUT / "region" / f"{r}.html").write_text(page(
            f"Public sector contracts — {REGION[r]} | BidBeacon",
            lede, f"Public contracts: {REGION[r]}", lede, items, rel_sectors, depth=2)); n += 1

    for b, items in buyers.items():
        lede = (f"{len(items)} open tenders currently advertised by {b}, worth {valrange(items)}. "
                f"Track new ones automatically with BidBeacon.")
        (OUT / "buyer" / f"{slug(b)}.html").write_text(page(
            f"{b} — open tenders & contracts | BidBeacon",
            lede, f"{b}: open tenders", lede, items, rel_sectors + rel_regions, depth=2)); n += 1

    # cornerstone guides + legal pages (from content/*.md)
    guide_links = _render_content("guides", rel_sectors + rel_regions)
    legal_links = _render_content("legal", [])
    n += len(guide_links) + len(legal_links)

    # hub index
    links = []
    hub_groups = [("By sector", [(s, f"sector/{slug(s)}.html") for s in sectors]),
                  ("By region", [(REGION[r], f"region/{r}.html") for r in regions]),
                  ("By buyer", [(b, f"buyer/{slug(b)}.html") for b in buyers])]
    if guide_links:
        hub_groups.append(("Guides", [(t, h.replace("seo/", "", 1)) for t, h in guide_links]))
    for label, pages_ in hub_groups:
        links.append(f"<h2 style='font-size:1rem;margin:20px 0 6px'>{label}</h2>")
        links.append("<nav class='related' style='border:none;margin:0;padding:0'>" +
                      "".join(f'<a href="{href}">{html.escape(t)}</a>' for t, href in pages_) + "</nav>")
    hub = page("Live UK & Scottish public contracts by sector, region & buyer | BidBeacon",
               "Browse live public-sector contract opportunities across Scotland and the UK by sector, region and buyer.",
               "Live public contracts, organised",
               f"{len(tenders)} open public-sector opportunities, grouped so you can find the ones that fit. "
               "All data live from Public Contracts Scotland and Contracts Finder.",
               [], [], depth=1).replace("<ul class=\"list\"></ul>", "".join(links))
    (OUT / "index.html").write_text(hub); n += 1

    # sitemap.xml + robots.txt (set BIDBEACON_BASE to your domain at deploy)
    import os
    base = os.environ.get("BIDBEACON_BASE", "https://bidbeacon.co.uk").rstrip("/")
    urls = [f"{base}/bidbeacon.html", f"{base}/seo/index.html"]
    urls += [f"{base}/seo/{p.relative_to(OUT).as_posix()}"
             for p in OUT.rglob("*.html") if p.name != "index.html"]
    today = date.today().isoformat()
    sm = ['<?xml version="1.0" encoding="UTF-8"?>',
          '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for u in urls:
        sm.append(f"<url><loc>{html.escape(u)}</loc><lastmod>{today}</lastmod></url>")
    sm.append("</urlset>")
    (SITE / "sitemap.xml").write_text("\n".join(sm))
    (SITE / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {base}/sitemap.xml\n")
    return {"pages": n, "sectors": len(sectors), "regions": len(regions),
            "buyers": len(buyers), "guides": len(guide_links), "sitemap_urls": len(urls)}


if __name__ == "__main__":
    print(json.dumps(build(), indent=2))
